#!/usr/bin/env python3
"""Embed an ndrv PEF into a C byte array so the trigger app can attach it to a
Name Registry node as the `driver,AAPL,MacOS,PowerPC` property (prop-based driver).

Usage: pef-to-blob.py <in.pef> <out.h> [symbolName]
   symbolName defaults to gEHCIPef (the UIM blob); pass e.g. gUsbDiskPef for others.
"""
import sys

def main():
    if len(sys.argv) not in (3, 4):
        sys.exit("usage: pef-to-blob.py <in.pef> <out.h> [symbolName]")
    sym = sys.argv[3] if len(sys.argv) == 4 else "gEHCIPef"
    with open(sys.argv[1], "rb") as f:
        data = f.read()
    lines = ["/* auto-generated by scripts/pef-to-blob.py from %s — do not edit */" % sys.argv[1],
             "/* Raw PEF container embedded so EHCITrigger can hand it to the OS (prop-based driver /",
             " * InstallDriverFromMemory). */",
             "static const unsigned char %s[] = {" % sym]
    row = []
    for i, b in enumerate(data):
        row.append("0x%02x," % b)
        if len(row) == 16:
            lines.append("  " + "".join(row))
            row = []
    if row:
        lines.append("  " + "".join(row))
    lines.append("};")
    lines.append("#define %sLen %dUL" % (sym, len(data)))
    lines.append("")
    with open(sys.argv[2], "w") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d PEF bytes -> %s[%d]" % (sys.argv[2], len(data), sym, len(data)))

if __name__ == "__main__":
    main()
